### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by Nicd** [Nicd/code-stats-atom#2]
[Enter steps to reproduce below:]

1. Enter "Find in project"
2. Use "Replace all" functionality

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.4
**Thrown From**: [code-stats-atom](https://github.com/Nicd/code-stats-atom) package, v1.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /Users/nicd/.atom/packages/code-stats-atom/lib/code-stats-atom.js:139

TypeError: Cannot read property 'getGrammar' of undefined
    at changeEvent (/Users/nicd/.atom/packages/code-stats-atom/lib/code-stats-atom.js:139:55)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1378:25
```

**Comment by SynapticSage** [comment]
You can also get this TypeError when using the Ever Notedown pacakge. If you create a new note and then attempt to send it to Evernote, same error type is thrown.

**Comment by Nicd** [comment]
I have a patch for this, will push next week.

**Comment by Nicd** [comment]
If you want to manually patch, remove line 139 in `code-stats-atom.js` and replace with:

```javascript
  const editor = atom.workspace.getActiveTextEditor();

  // In some situations, such as "Replace all", the editor is undefined. If that is the case,
  // abort
  if (editor == null) {
    return;
  }

  const grammar = editor.getGrammar();
```

**Comment by Nicd** [comment]
@SynapticSage can you check if the bug is fixed now?

**Comment by SynapticSage** [comment]
Works like a charm 👍 Excellent!
