### ISSUE TITLE
Lingering massive XP issue

### ISSUE THREAD

**Issue by Nicd** [Nicd/code-stats-atom#3]
Massive XP is granted in some currently unknown situation. In one case 10k XP was sent in one Pulse. Since change events are restricted to 200 XP maximum, the event must have been called at least 50 times by Atom. Should investigate the reason for so many calls.

**Comment by agustif** [comment]
https://github.com/soapskyway/keycount

**Comment by Nicd** [comment]
Thanks @agustif, I'll take a look at it. Looks like it could be a solution, but I will have to do some testing.

**Comment by Nicd** [comment]
I've written a new version of the plugin that attempts to fix these issues by listening to keystrokes instead of editor changes (thanks for the tip @agustif).

I'm looking for people to test it before I release it. To test, run the following commands (if `apm` is not in your path, use "Install shell commands" from Atom):

```
# To clone and install plug in in development mode
apm develop code-stats-atom

# To start Atom in development mode, will use the new version of the plugin
atom -d
```

This should leave your normal plugin version unaffected (if you start Atom normally, it should use the old version). The development version has an XP counter in the status bar that helps see how XP is being granted -- this may be dropped from the eventual release version. Known issue is that some key combinations that don't add characters, like ctrl+s etc. give 1 XP in certain situations. That seems to be unavoidable, but I think the XP received that way will be negligible when compared to the actual typing XP. But I would like to hear your comments, so please comment your experiences below.

**Comment by agustif** [comment]
Hey, Thats nice, will try the plugin ASAP, but Im not coding much later

**Comment by Nicd** [comment]
Hey @agustif @jrdepew have you had time to test? Any comments?

**Comment by jrdepew** [comment]
Hi Mikko,

I have been testing today and trying to see if I can reproduce the XP
error. So far I have not seen a repeat. Copy+Paste does not count every
character/line, and holding (sleeping) on a key does not recognize either.
I have lower threshold for crashing, in Atom, but that may be related to
other plugins.

thanks,
Jeremy

**Comment by Nicd** [comment]
Hm, what kind of crashes have you seen? If they are related to code-stats-atom, please file bug reports with stack traces if you can.
